### ISSUE TITLE
请问现在是不是历史结束了

### ISSUE THREAD

**Issue by KissesJun** [DGCK81LNN/lspmt#2]
翻了翻帖子，发现好像已经终结了

**Comment by DGCK81LNN** [comment]
您好，好像的确是这样，在此油猴脚本制作之初，贴吧那边似乎就已经不大活跃，本人制作此油猴脚本仅供娱乐，前一阵我也发现一些「文件传输工具」已经404掉了。

**Comment by DGCK81LNN** [comment]
本工具现已失效：#3
